before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - mkdir -p lib bin
  - rustc --out-dir lib ./src/cgmath/lib.rs
  - rustc --out-dir bin --test -L ./lib ./src/test/test.rs
  - rustc --out-dir bin --test -L ./lib ./src/bench/bench.rs
  - ./bin/test
#  - ./bin/bench --bench
